# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ori}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Fortuna"]
  s.date = %q{2011-01-02}
  s.description = %q{Object-Oriented RI for IRB Console}
  s.email = %q{alex.r@askit.org}
  s.extra_rdoc_files = [
    "README.html",
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.html",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "lib/misc/method_aliases.rb",
    "lib/ori.rb",
    "lib/ori/auto_config.rb",
    "lib/ori/colorize.rb",
    "lib/ori/config.rb",
    "lib/ori/extensions.rb",
    "lib/ori/extensions/object/ri.rb",
    "lib/ori/internals.rb",
    "lib/ori/library.rb",
    "lib/ori/list_method.rb",
    "lib/ori/request.rb",
    "lib/ori/tools.rb",
    "ori.gemspec",
    "samples/NOTES",
    "samples/basic_extension.rb",
    "samples/basic_inheritance.rb",
    "samples/self_singletons.rb",
    "samples/singleton_class_includes_module.rb",
    "spec/auto_config_spec.rb",
    "spec/colorize_spec.rb",
    "spec/inspector_spec.rb",
    "spec/internals_spec.rb",
    "spec/list_method_spec.rb",
    "spec/request_spec.rb",
    "spec/site/NOTES",
    "spec/site/library_spec.rb",
    "spec/site/spec_helper.rb",
    "spec/spec_helper.rb",
    "spec/tools_spec.rb"
  ]
  s.homepage = %q{http://github.com/dadooda/ori}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Object-Oriented RI for IRB Console}
  s.test_files = [
    "spec/auto_config_spec.rb",
    "spec/colorize_spec.rb",
    "spec/inspector_spec.rb",
    "spec/internals_spec.rb",
    "spec/list_method_spec.rb",
    "spec/request_spec.rb",
    "spec/site/library_spec.rb",
    "spec/site/spec_helper.rb",
    "spec/spec_helper.rb",
    "spec/tools_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

